"""remove_groq_config

Revision ID: 9e232364c0ac
Revises: b2a3c4d5e6f7
Create Date: 2026-01-04 20:53:22.743235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e232364c0ac'
down_revision: Union[str, Sequence[str], None] = 'b2a3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groq_configs_id'), table_name='groq_configs')
    op.drop_table('groq_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groq_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('api_keys', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('usage_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('groq_configs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('groq_configs_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('groq_configs_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_groq_configs_id'), 'groq_configs', ['id'], unique=False)
    # ### end Alembic commands ###
