"""add_refresh_tokens_to_user

Revision ID: fa1496962933
Revises: d994578f55f2
Create Date: 2025-12-22 16:51:06.694537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1496962933'
down_revision: Union[str, Sequence[str], None] = 'd994578f55f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_tokens', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_tokens')
    # ### end Alembic commands ###
